quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.headers=accept, authorization, content-type
quarkus.http.cors.methods=GET, POST, PATCH, DELETE
quarkus.datasource.db-kind = mysql
quarkus.datasource.username = ${DB_USERNAME}
quarkus.datasource.password = ${DB_PASSWORD}
quarkus.datasource.jdbc.url = ${DB_URL}
